### ISSUE TITLE
Apps in libertine open everything in a new window

### ISSUE THREAD

**Issue by YougoCodes** [ubports/libertine#10]
Device: FP2
OS: ubports ubuntu Touch 16.04/devel

Use case: 
1. open an app from the libertine scope.
-the app starts.
2. Press a menu item.
- expected behavior: drop down menu opens
- witnessed behavior: a new window is created containing the drop down menu. Choosing a menu option closes the extra window but the command is not forwarded to the main app. 
3. Hover cursor over a GUI element to trigger a tooltip
- expected behavior: tooltip appears. Moving the cursor away causes the tooltip to close
- witnessed behavior: tooltip is opened in a new window. Clicking on the tooltip causes the extra window to close
4. When available, drag a toolbar away from it’s docked position to make it a floating toolbar
- expected behavior: toolbar becomes a floating toolbar
- witnessed behavior: toolbar is given it’s own new window

Assessment: mir/xmir/? Seems confused as to what needs its own windows (dialogue boxes, independent apps launched by the other app, e.g. typing ‘gedit’ in a terminal, etc.) and what doesn’t (drop down menus, contextual menus, tooltips, etc.)

This renders libertine apps nearly unusable. I first started noticing this behavior after updating from 15.04 to 16.04

Attached you will find screenshots of Libreoffice writer opened with a floating toolbar and a menu opened in a new window, and a tooltip opened in a new window.
![fbb204db-8464-4399-a406-d31191280ff9](https://user-images.githubusercontent.com/23282697/44864030-09339680-ac7f-11e8-9f6b-564d8d9238ff.png)
![8e5b8aa8-ff79-4989-88c5-1f484a84728b](https://user-images.githubusercontent.com/23282697/44864033-09339680-ac7f-11e8-9a0d-7a54a9a29d82.png)
![9a43c2a2-fc5f-4d1b-9899-98e748376e65](https://user-images.githubusercontent.com/23282697/44864034-09cc2d00-ac7f-11e8-8b87-cb15e35982fe.png)
![b8e7ef21-ed8e-4604-b893-eb4851caf40b](https://user-images.githubusercontent.com/23282697/44864036-09cc2d00-ac7f-11e8-806d-8d9e0a620ea3.png)

**Comment by eitzenbe** [comment]
i can confirm this bug, it affects nearly all native x apps (firefox, audacity, thunderbird, ....) on Amaris BQ10 FHD

**Comment by arubislander** [comment]
There is a workaround / fix for this issue [here](https://forums.ubports.com/post/12957)
