### ISSUE TITLE
Modification of Libertine container application display

### ISSUE THREAD

**Issue by Billdemoncho** [ubports/libertine#11]
Hello, 
My meizu pro5 is in 16.04 recently.
I want to modify the theme or applications of the Libertine container, for a better use. Because in the state, no application can be used correctly.
To do this, I want to change the width of the scroll bar and buttons.
Can you guide me?

I was able to resize the pages by adapting the definition in an Xdefault file but I couldn't find for the scroll-bar and buttons. I was thinking of a css file under gtk, but I can't find it.

thank you for your feedback

**Comment by ShadowEO** [comment]
Scroll bar and UI theming would be a .gtkrc-2.0 or .gtkrc-3.0 file in the libertine container's home directory.

To use other GTK themes, you'll want to make sure the packages are installed into the libertine container. Another option for changing things is to install lxappearance.

**Comment by tallero** [comment]
@Billdemoncho 
To change GTK+ applications theme:

```bash
    # Enter the container
    libertine-container-manager exec -i CONTAINER_ID -c "/bin/bash"
    # install gnome-tweak
    apt install gnome-tweak-tool
    # exit the container
    exit
    # run gnome-tweak-tool
    ubuntu-app-launcher xenial_gnome-tweak-tool_0.0
 ```
To fix UI scaling, for each application you want to fix:

- enter the container
- edit the corresponding desktop file in `/usr/share/applications`, prefixing `env GDK_SCALE=X` in the `Exec` command, where `X` is an integer. Most application are well rendered at 3.

You can also enable touchscreen support prefixing `GTK_DEBUG=touchscreen`.

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/11
