### ISSUE TITLE
Libertine Apps don't accept mouse or touch input beyond approx. 2/3rd of the window. window input area is always portrait, even when device is landscape 

### ISSUE THREAD

**Issue by YougoCodes** [ubports/libertine#13]
Device: bq Aquarius M10 hd
device: fairphone 2 
os: Ubports Ubuntu touch 16.04/RC 

Steps To reproduce:

- create a container 
- Add app, for example libre office calc
- Start app
- Push buttons or select gui elements on the right 1/3 of the window

Expected Response
- App responds accordingly

Actual Behavior
-app Does not respond to input beyond approx. 2/3 rd of the window. 

tested this in windowed and staged mode, with device in portrait and landscape mode. the effect is the same. at some point to the right, the app no longer responds.

@dobey suspects some interaction between xmir and side stage

willing to test settings and apps, supply logs

**Comment by YougoCodes** [comment]
new observation: 
the responsive part of the window has the width of the screen in portrait mode, no matter what orientation the device is in, or what size the window is. staged or windowed mode doesn't matter. everything beyond that point is 'off screen' and as such not accessible for input

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/13
