### ISSUE TITLE
I cant install windows fonts from libertine

### ISSUE THREAD

**Issue by lotfi-123** [ubports/libertine#28]
Device:one plus one  
 https://i.postimg.cc/WbsR4TDC/screenshot20190119-182243122.png

**Comment by balcy** [comment]
one way via command line would be
`libertine-container-manager exec -c bash` (if you have several containers see http://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html#shell-access)
inside the container, run
`echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections`
and then
`apt-get install ttf-mscorefonts-installer`
(like https://askubuntu.com/questions/16225/how-can-i-accept-the-microsoft-eula-agreement-for-ttf-mscorefonts-installer/25614#25614 but without the sudo)

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/28
