### ISSUE TITLE
packages selected from list are not installed

### ISSUE THREAD

**Issue by arubislander** [ubports/libertine#33]
Searching for a package by name produces a list. Selecting to install a downloaded package also produces a list.
In both cases selecting a package from the list to install does not install the package.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed, but other error spotted. After searching a package by name (eg. curl), a ```Package Search Results``` list ist produced. After tapping on a package in list, package is installed.

Error spotted: When entering a name in search dialog, the "ok" button does not work, you have to hit enter to search.

**Comment by arubislander** [comment]
Thanks for your review. The error you spotted is not a regression. (not claiming you said it was, just making it clear) Rather it is a general issue in QML. When tapping on a button, the TextField does not loose input focus, and so the text entered is not registered (ie, the button still thinks the field is empty). If there is not already an issue raised against this, feel free to raise one)
