### ISSUE TITLE
Libertine still adds Stable Phone Overlay PPA

### ISSUE THREAD

**Issue by dobey** [ubports/libertine#44]
Though we no longer use the stable-phone-overlay PPA which Canonical used to maintain for the phone images, in the main Ubuntu Touch rootfs, it is still being added by libertine when creating new containers. This can cause some compatibility issues by mixing the PPA packages with packages from the UBports repo.

**Comment by UniversalSuperBox** [comment]
Fixed by https://github.com/ubports/libertine/pull/45

**Comment by jezek** [comment]
There is OTA10 call for testing in progress. How can we test this?

**Comment by dobey** [comment]
> There is OTA10 call for testing in progress. How can we test this?

Create a new libertine container, and verify `ppa.launchpad.net` does not appear in the output when running `apt-get update` inside the container.

**Comment by jezek** [comment]
FP2 (2019-W32) - Fixed

steps:
1. Opened libertine containers from settings and added container with name ```test``` and no password
2. Waited... container with distribution xenial, id ```xenial-2``` and  name ```Ubuntu 16.04.6 LTS(2)``` was created and ready
3. In terminal runned ```libertine-container-manager exec -i xenial-2 -c "apt-get update"```
4. Checked if there in no ```ppa.launchpad.net``` in the output:
```bash
Už existuje:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Už existuje:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease
Ign:3 https://repo.ubports.com xenial InRelease
Už existuje:4 https://repo.ubports.com xenial Release
Načítavajú sa zoznamy balíkov... Hotovo
```
