### ISSUE TITLE
Python depends on lsb_release

### ISSUE THREAD

**Issue by vanyasem** [ubports/libertine#5]
`lsb_release` is debian-specific and is not available on other distros (causing the systemd service to fail)

**Comment by vanyasem** [comment]
Troubling file: `HostInfo.py`

**Comment by vanyasem** [comment]
And also `python-distro-info` which is also debian-specific

**Comment by vanyasem** [comment]
I am not sure if it's even a valid issue considering libertine is a tool for running `deb-based` applications

**Comment by NeoTheThird** [comment]
This actually touches on a pretty basic question: Will desktop-distros that use Unity 8 have a read-only file system and only use click packages? I don't think that will be the case, it would make more sense for them to just install packages from the normal sources, so you don't really need libertine. XMir can be used without, and Wayland+Mir is not a problem anyways. So i'd say you can go ahead and ignore Libertine for Arch. The main reason we use image-based-upgrades is the hardware limitations of phone storage chips. They are not meant to be constantly written to, unlike proper hard drives or SSDs.

**Comment by dobey** [comment]
@NeoTheThird It may not be a necessity on traditional PC systems, but I think it can be useful as a security enhancement in such cases, by pushing legacy apps into a container environment. I've started some work on ubuntu-app-launch to get rid of xmir and make libertine optional, but it creates a problematic situation with running some legacy apps, until Xwayland is working with unity8.

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/5
