### ISSUE TITLE
Tooltip fix breaks ubuntu-app-launcher

### ISSUE THREAD

**Issue by tallero** [ubports/libertine#57]
After having partly fixed #10 with the fix there mentioned (i.e. add the `-flatten` option to `/usr/bin/libertine-xmir`), the command `ubuntu-app-launch` breaks. 

Here is the log (for `gnome-tweak-tool` but it is the same with everything now:

```bash
** (process:16908): WARNING **: Unable to connect to Upstart bus: Cannot autolaunch D-Bus without X11 $DISPLAY
error calling result "Not connected to D-Bus server"
error calling result "Not connected to D-Bus server"
lastError - no arguments?
error calling result "Not connected to D-Bus server"
lastError - no arguments?
error calling result "Not connected to D-Bus server"
lastError - no arguments?

** (process:16908): WARNING **: Unable to start app 'xenial_gnome-tweak-tool_0.0': Invalid app ID: xenial_gnome-tweak-tool_0.0
```

**Comment by dobey** [comment]
Where are you running this command from exactly?

**Comment by tallero** [comment]
> Where are you running this command from exactly?

Inside an ssh session, but I just tested from terminal device and it is working, but previously it was working in ssh, too.

**Comment by dobey** [comment]
> > Where are you running this command from exactly?
> 
> Inside an ssh session, but I just tested from terminal device and it is working, but previously it was working in ssh, too.

Were you actually inside the container  for this instance? It looks like the environment was cleared (and so couldn't connect to dbus), which would happen if you were inside a libertine container shell. From just an ssh session to the host OS, yes, it does work (I use this all the time, myself).

So I'm going to close this. If it continues to happen though, feel free to reopen.

**Comment by tallero** [comment]
Of course I weren't inside the container when I run the command, and it is still happening (not working in `ssh` but working on `qterminal`).

Really do not know much of Upstart, aside from basic commands, can you give me an hint to solve this?

Also, I am not entirely sure this depends on `-flatten`, or at least the effect is not reversible.

**Comment by dobey** [comment]
What do you mean it's working on `qterminal` exactly? That is not something that's shipped on the device, nor in the open store.

I cannot see your device, so I have no idea what exactly you are doing here.

**Comment by tallero** [comment]
>What do you mean it's working on `qterminal` exactly? That is not something that's shipped on the device, nor in the open store.

I meant the pre-installed terminal on the device (`com.ubuntu.terminal`?), which I believed it was called `qterminal`.

**Comment by dobey** [comment]
Have you logged out and instead initiated a new ssh session to try in?

**Comment by tallero** [comment]
I rebooted the phone two or three times since then.

**Comment by dobey** [comment]
What does `env | grep SESSION` say? Have you modified `~/.profile` or `~/.bashrc` at all? Did you change the default shell?

**Comment by tallero** [comment]
It was definitely `zsh` not sourcing both `.profile` and `.bashrc`.

```bash
    XDG_SESSION_ID=13
    UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/UUID/XXXXX
    DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-XXXXXXXXXX
```

My bad, really sorry for this one, I did not know zsh ignored `.profile`.
I will try to load them the same and see if the problem solves.
