### ISSUE TITLE
Libertine app menus are distorted

### ISSUE THREAD

**Issue by zubozrout** [ubports/libertine#59]
- Device: Meizu MX4 (arale)
- Channel: edge
- Build: any

### Steps to reproduce
Unlike on current stable/devel Xenial releases the in-app menus fortunately no longer open in separate windows but pop up right where they should. However, most of them except some custom ones (something in the address bar of Firefox) are completely distorted. Lines, icons, texts - everything looks like if you took a photo of a billboard while passing around at 200 km/h.

One thing to note though is that when clicked on items in this menu some actions are triggered so I suspect this to be a purely graphical issue.

### Expected behavior
Menus are not distorted.

### Actual behavior
Menus are distorted and one can't make out anything but straight horizontal lines which seem to stay visible unchanged in some cases.

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/59
