### ISSUE TITLE
Container apparently deleted without user interaction

### ISSUE THREAD

**Issue by tallero** [ubports/libertine#64]
My default 'xenial' container just disappeared from containers list. The command `libertine-container-manager list` returns nothing. Before disappearing libertine crashed the phone opening `lxterminal`.

In `$XDG_DATA_HOME/libertine-container` there is only the `user-data` directory.

Device is `hammerhead`.

**Comment by dobey** [comment]
Did you happen to delete everything under `~/.cache/` perhaps?

**Comment by tallero** [comment]
> Did you happen to delete everything under `~/.cache/` perhaps?

I do not remember doing it but it could be at this point. So the container rootfs is in `~/.cache/libertine-container/id/rootfs`.

It seems to me an incorrect implementation of the *XDG Base Directory Specification*, if there is no tool to automatically regenerate the files in the cache at runtime:

>`$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to $HOME/.cache should be used.
>
>[Source](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Rootfs should belong to `$XDG_DATA_HOME` instead. Semantically it makes sense and it even mirrors the `system.img` and `userdata.img` location in ubports recovery root (`/data`).

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/64
