### ISSUE TITLE
Make libertine self dependent

### ISSUE THREAD

**Issue by mariogrip** [ubports/libertine#69]
We should make libertine self dependent without needing ubuntu-app-launch to launch apps. To achieve this we should symlink our desktop files to local application folder and make the exec run libertine that then will run the libertine app.

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/69
