### ISSUE TITLE
Container distribution different to the host distribution?

### ISSUE THREAD

**Issue by seteahconnoc** [ubports/libertine#94]
Hello.

Thank you for providing libertine. Please, excuse me, if this issue is too obvious: Is it possible to install a libertine container where the container distribution differs from the host distribution? If so: How do I achieve this?

I am using a OnePlus One bacon, OTA-12, and I am getting this (german) error message:
```
phablet@ubuntu-phablet:~$ libertine-container-manager create -i bionic -d bionic
libertine-container-manager:88: ERROR: create():	Die Container Distribution muss die selbe wie die des Hosts sein um chroot basierte Container nutzten zu können. Bitte nutzte 'xenial' or die -d/--distro Option.
```
Looking here ...
[http://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html](url)
... and here ...
[http://kylenubuntu.blogspot.com/2016/07/running-x-apps-on-ubuntu-devices.html](url)
... brought me so far, that it seeems to be impossible. Quote: "The container must be the same Ubuntu series as the device."

But I just wanted to be sure.

_Background information: I am aiming to install a desktop application where I'm in need of Python3.7, which leads me to packages dependency problems. I am already looking for an alternative way on the appropriate forum._

Anyway, thanks to UBports community for doing a great job.

**Comment by seteahconnoc** [comment]
BTW: I solved my original dependency problem. This issue now is of academic nature - at least for me.

**Comment by dobey** [comment]
Right, libertine only supports using the same Ubuntu series as the host is. If you need a newer version of something, you'll need it built for that Ubuntu release (in this case 16.04). You can for example get a newer version of Python into a container, using the deadsnakes PPA.

**Comment by seteahconnoc** [comment]
@dobey Thank you.
I'm proud to say that I figured out the deadsnakes way by myself. As said above: That leads me to other package dependency problems. - But, that's all history now, for I figured out an alternative.
